### ISSUE TITLE
Switched to a production server 

### ISSUE THREAD

**Issue by Eblohm** [Eblohm/tc359_rails_final#1]
@chrisvfritz

We looked at this in class because BuiltWith wasn't showing which production server I was using, but here's the heroku logs

2015-04-06T16:03:27.129251+00:00 app[web.1]: 
2015-04-06T16:03:27.129319+00:00 app[web.1]: You can stop Phusion Passenger Standalone by pressing Ctrl-C.
2015-04-06T16:03:27.129122+00:00 app[web.1]: Environment: production
2015-04-06T16:03:27.129396+00:00 app[web.1]: ===============================================================================

**Comment by chrisvfritz** [comment]
:+1: Looks good!

**Comment by Eblohm** [comment]
@chrisvfritz Would it be possible for a skill to be added to Codekwondo that adds an account creation system to the app? After doing the authentication system last week I'm really interested in adding a whole login/sign-up system to the app

**Comment by chrisvfritz** [comment]
Definitely! Would you be most interested in building it from scratch or using a gem like devise to do most of the heavy lifting?

**Comment by Eblohm** [comment]
I would love to build it from scratch, learning how to do everything that goes into a system like that would be really cool.

**Comment by chrisvfritz** [comment]
You got it. I'll be adding that soon then.

**Comment by chrisvfritz** [comment]
[Check it out!](http://codekwondo.herokuapp.com/skills/58)

**Comment by Eblohm** [comment]
Perfect! Thanks!
