### ISSUE TITLE
Integrate Twitter Bootstrap into Rails

### ISSUE THREAD

**Issue by Eblohm** [Eblohm/tc359_rails_final#3]
@chrisvfritz I believe I finished this skill!

**Comment by chrisvfritz** [comment]
I don't think I see where this criterion is completed:

> You are overriding at least 3 Bootstrap variables (without using !important), for visible effect in your app.

Let me know if I've just missed it somewhere.

**Comment by Eblohm** [comment]
OH! I completely misunderstood what you meant, I changed the bootstrap code with regular CSS. I just updated it, and now it's been changed in SCSS variables.

I also mirrored your directory structure, so the variables file is in app/assets/stylesheets/bootstrap/variables.scss

**Comment by chrisvfritz** [comment]
:+1: Excellent!
