### ISSUE TITLE
Use Slim as an alternative to ERB in Rails

### ISSUE THREAD

**Issue by Eblohm** [Eblohm/tc359_rails_final#4]
@chrisvfritz

Just finished converting all the HTML files to Slim!

**Comment by chrisvfritz** [comment]
This looks great, apart from one thing. It looks like a bunch of hard tabs slipped in during the conversion process. Can you clean these up and get us back to all two-space soft tabs?

**Comment by Eblohm** [comment]
Just fixed that, pushed the changes to Github and Heroku!

**Comment by chrisvfritz** [comment]
This and the other issue look much better! There are just three files left where the hard tabs remain:

```
Searching 88 files for "\t" (regex)

app/assets/stylesheets/application.scss:
   18  
   19  .formWidth {
   20: 	width:20%;
   21  }

app/views/layouts/application.html.slim:
    3    head
    4      title TC359 Rails Final
    5:     = stylesheet_link_tag	'application', media: 'all'
    6:     = javascript_include_tag	'application'
    7      = csrf_meta_tags
    8  

app/views/static/about.html.slim:
    1: h1 Static#about	
    2  p This is the about page!
```

**Comment by Eblohm** [comment]
Fixed those! All hard tabs should be gone!

**Comment by chrisvfritz** [comment]
:+1: Fantastic! For future reference, you can search through your entire project in Sublime with Cmd/Ctrl+Shift+P. From there, I toggled regex on and then just typed in `\t` which is the regex representation of a tab character.

**Comment by Eblohm** [comment]
Perfect! I was actually gonna ask you what you used to search for that, haha. Thanks!
